development:
  adapter: mysql
  encoding: utf8
  database: maximus
  username: root
  password: "mustdie"
  host: localhost
production:
  adapter: mysql
  encoding: utf8
  database: maximus
  username: root
  password: "mustdie"
  host: localhost

